/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMain;

//import static FormMain.Principal.jCheckBoxAdicionarHer;
import conexaoBD.conexaoBaseDados;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Herdeiro extends javax.swing.JFrame {

    /**
     * Creates new form Herdeiro
     */
    int x, y;
    conexaoBaseDados cbd = new conexaoBaseDados();
   
    public Herdeiro() {
        initComponents(); 
        cbd.Conectar();
        ShowData();
    }
    
    public void ShowData() {
        Date d = new Date();
        SimpleDateFormat formatar = new SimpleDateFormat("yyyy/MM/dd");
        jLabelData.setText(formatar.format(d));
    }
    
    public void listaHerdeiroH() {    
        cbd.executaSQL("select * from herdeiro where  bi_benificiar like'%" + jLabelBIH.getText() + "%'");
        jLabelTituloH.setText("Verifique:");
        try {
            int soma = 0;

            while (cbd.resultado.next()) {
                soma = soma + 1;
            }
     
            if(soma == 0 ){
                jLabelTituloH.setText("Adicionar a Primeira Pessoa:");
                jLabelTituloH.setForeground(Color.black);
                jButtonAdicionar.setEnabled(true);
               
            }else if(soma == 1){
                jLabelTituloH.setText("Adicionar a Segunda Pessoa:");
                jLabelTituloH.setForeground(Color.black);
                jButtonAdicionar.setEnabled(true);
                
            }else if (soma == 2) {
                 jLabelTituloH.setText("Limite Atingido de Herdiros");
                 jLabelTituloH.setForeground(Color.RED);
                jButtonAdicionar.setEnabled(false);
                jLabelAviso.setForeground(Color.red);              
            }
        } catch (Exception erro) {
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelTituloH = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextNomeHerdeiro = new javax.swing.JTextField();
        jLabelResiPr = new javax.swing.JLabel();
        jComboBoxParentescoH = new javax.swing.JComboBox<>();
        jLabelGrauParentesco = new javax.swing.JLabel();
        jComboBoxProviniaH = new javax.swing.JComboBox<>();
        jTextDistritoMH = new javax.swing.JTextField();
        jLabelDistMunicipal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextquarteraoNumeroH = new javax.swing.JTextField();
        jLabelAV = new javax.swing.JLabel();
        jTextAvenidaH = new javax.swing.JTextField();
        jTextContacto = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jTextCasaNumeroH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelAviso = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelBIH = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jLabelLocalidade = new javax.swing.JLabel();
        jTextLocalidadeH = new javax.swing.JTextField();
        jLabelNomeBenificiarioH = new javax.swing.JLabel();
        Femenino = new javax.swing.JRadioButton();
        jLabelContacto = new javax.swing.JLabel();
        Masculino = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabelData = new javax.swing.JLabel();
        jLabelChavePrimariaH = new javax.swing.JLabel();
        jLabelChavePrimariaH1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Herdeiro ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel14MouseDragged(evt);
            }
        });
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 50));

        jLabelTituloH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabelTituloH, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNome.setText("Nome:");
        jPanel1.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jTextNomeHerdeiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNomeHerdeiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextNomeHerdeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNomeHerdeiroKeyReleased(evt);
            }
        });
        jPanel1.add(jTextNomeHerdeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 380, 20));

        jLabelResiPr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResiPr.setText("Residente na Privíncia de:");
        jPanel1.add(jLabelResiPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, 20));

        jComboBoxParentescoH.setBackground(new java.awt.Color(0, 153, 0));
        jComboBoxParentescoH.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxParentescoH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Pai", "Mae", "Esposa", "Esposo", "Irmão", "Irmã", "Filho", "Filha", "Primo", "Prima", "Neto", "Neta", "Sobrino ", "Sobrinha", "Avô", "Avó" }));
        jComboBoxParentescoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxParentescoHActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxParentescoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, 20));

        jLabelGrauParentesco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelGrauParentesco.setText("Grau de Parentesco:");
        jPanel1.add(jLabelGrauParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jComboBoxProviniaH.setBackground(new java.awt.Color(0, 153, 0));
        jComboBoxProviniaH.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxProviniaH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Maputo (Matola)", "Maputo (cidade)", "Gaza", "Inhambane", "Sofala", "Manica", "Tete", "Zambézia", "Nampula", "Cabo Delgado", "Niassa" }));
        jComboBoxProviniaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProviniaHActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProviniaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 20));

        jTextDistritoMH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextDistritoMH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextDistritoMH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextDistritoMHKeyReleased(evt);
            }
        });
        jPanel1.add(jTextDistritoMH, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 190, 20));

        jLabelDistMunicipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDistMunicipal.setText("Distrito Municipal:");
        jPanel1.add(jLabelDistMunicipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Q.nº:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, 20));

        jTextquarteraoNumeroH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextquarteraoNumeroH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jPanel1.add(jTextquarteraoNumeroH, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 20));

        jLabelAV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAV.setText("Av./Rua:");
        jPanel1.add(jLabelAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        jTextAvenidaH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextAvenidaH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextAvenidaH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAvenidaHKeyReleased(evt);
            }
        });
        jPanel1.add(jTextAvenidaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 250, 20));

        jTextContacto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextContacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextContactoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, 20));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexo.setText("Sexo:");
        jPanel1.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jTextCasaNumeroH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCasaNumeroH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jPanel1.add(jTextCasaNumeroH, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Casa nº:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, 20));

        jLabelAviso.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabelAviso.setText("* Adicione no maximo 2 herdeiros. ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("* Em caso de morte ou dessaparecimento físico, os bens pessoais devem ser entregues á;");

        jLabelBIH.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAviso)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBIH, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelAviso)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBIH, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 540, 50));

        jButtonAdicionar.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionar.setText("Adcionar");
        jButtonAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionar.setEnabled(false);
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, -1));

        jLabelLocalidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLocalidade.setText("Localidade:");
        jPanel1.add(jLabelLocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, 20));

        jTextLocalidadeH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLocalidadeH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextLocalidadeH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextLocalidadeHKeyReleased(evt);
            }
        });
        jPanel1.add(jTextLocalidadeH, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 140, 20));

        jLabelNomeBenificiarioH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeBenificiarioH.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(jLabelNomeBenificiarioH, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 340, 20));

        Femenino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSexo.add(Femenino);
        Femenino.setText("Femenino");
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });
        jPanel1.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabelContacto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContacto.setText("Contacto:");
        jPanel1.add(jLabelContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        Masculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupSexo.add(Masculino);
        Masculino.setText("Masculino");
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Check");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 110, 20));

        jLabelChavePrimariaH.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelChavePrimariaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));

        jLabelChavePrimariaH1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelChavePrimariaH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(557, 369));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:      
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:       
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel13MouseDragged

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel14MouseDragged

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        String sexo;

        if (Femenino.isSelected()) {
            sexo = "Femenino";
        } else {
            sexo = "Masculino";
        }

        if (jTextNomeHerdeiro.getText().equals("")) {
            jLabelNome.setForeground(Color.red);
        } else if (jComboBoxParentescoH.getSelectedItem().equals("Selecione:")) {
            jLabelGrauParentesco.setForeground(Color.red);
        } else if (jComboBoxProviniaH.getSelectedItem().equals("Selecione:")) {
            jLabelResiPr.setForeground(Color.red);
        } else if (jTextDistritoMH.getText().equals("")) {
            jLabelDistMunicipal.setForeground(Color.red);
        } else if (jTextLocalidadeH.getText().equals("")) {
            jLabelLocalidade.setForeground(Color.red);
        } else if (jTextAvenidaH.getText().equals("")) {
            jLabelAV.setForeground(Color.red);
        } else if (jTextContacto.getText().equals("")) {
            jLabelContacto.setForeground(Color.red);
        } else if (Femenino.isSelected() == false && Masculino.isSelected() == false) {
            jLabelSexo.setForeground(Color.red);
        } else {
            try {
                PreparedStatement inserirHerdeiro = cbd.conexao.prepareStatement("INSERT INTO herdeiro (nome,grau_parentesco,residente_provincia,distrito_municipal,localidade,avendida_rua,quart_numero,casa_numero,sexo,bi_benificiar,data) VALUE (?,?,?,?,?,?,?,?,?,?,?)");
                inserirHerdeiro.setString(1, jTextNomeHerdeiro.getText());
                inserirHerdeiro.setString(2, (String) jComboBoxParentescoH.getSelectedItem());
                inserirHerdeiro.setString(3, (String) jComboBoxProviniaH.getSelectedItem());
                inserirHerdeiro.setString(4, jTextDistritoMH.getText());
                inserirHerdeiro.setString(5, jTextLocalidadeH.getText());
                inserirHerdeiro.setString(6, jTextAvenidaH.getText());
                inserirHerdeiro.setString(7, jTextquarteraoNumeroH.getText());
                inserirHerdeiro.setString(8, jTextCasaNumeroH.getText());
                inserirHerdeiro.setString(9, sexo.toString());
                inserirHerdeiro.setString(10, jLabelBIH.getText());
                inserirHerdeiro.setString(11, jLabelData.getText()); 
                
                if (jLabelChavePrimariaH.getText().equals("Existe!")) {
                    JOptionPane.showMessageDialog(null, "Esse Contacto Já Exite!");
                } else {                 
                     inserirHerdeiro.executeUpdate();
                     jButtonAdicionar.setEnabled(false);
                }              
                
                String idEstrageiro = "";
                cbd.pesquisar = cbd.conexao.createStatement();
                String sql = "select max(id) from herdeiro ";
                cbd.resultado = cbd.pesquisar.executeQuery(sql);

                if (cbd.resultado.next()) {                
                    idEstrageiro = cbd.resultado.getString(1);
                }

                PreparedStatement inserircontacto = cbd.conexao.prepareStatement("INSERT INTO herdeiro_telefone (telefone,id) VALUE (?,?)");
                inserircontacto.setString(1, jTextContacto.getText());
                inserircontacto.setString(2, idEstrageiro.toString());
               
                inserircontacto.executeUpdate();
                jTextContacto.setText("");
                
                Dialog l = new Dialog();
                l.setVisible(true);
                listaHerdeiroH();

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro na Inseção dos Dados!" + erro);
            }
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTextNomeHerdeiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomeHerdeiroKeyReleased
        // TODO add your handling code here:
        jLabelNome.setForeground(Color.black);
    }//GEN-LAST:event_jTextNomeHerdeiroKeyReleased

    private void jTextDistritoMHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDistritoMHKeyReleased
        // TODO add your handling code here:
        jLabelDistMunicipal.setForeground(Color.black);
    }//GEN-LAST:event_jTextDistritoMHKeyReleased

    private void jTextLocalidadeHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextLocalidadeHKeyReleased
        // TODO add your handling code here:
        jLabelLocalidade.setForeground(Color.black);
    }//GEN-LAST:event_jTextLocalidadeHKeyReleased

    private void jTextAvenidaHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAvenidaHKeyReleased
        // TODO add your handling code here:
        jLabelAV.setForeground(Color.black);
    }//GEN-LAST:event_jTextAvenidaHKeyReleased

    private void jTextContactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContactoKeyReleased
        // TODO add your handling code here:
        jLabelContacto.setForeground(Color.black);
         try {
            cbd.executaSQL("select * from herdeiro_telefone  where telefone like'%" + jTextContacto.getText() + "%'");
            cbd.resultado.next();
            if (cbd.resultado.getString("telefone").equals(jTextContacto.getText())) {
               // jButtonAdicionar.setEnabled(false);
                jLabelChavePrimariaH.setText("Existe!");                
            } else {
               // jButtonAdicionar.setEnabled(true);
                jLabelChavePrimariaH.setText("");
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null,"Caracter invalido!");
        }

        try {
            int i = Integer.parseInt(jTextContacto.getText());
            jLabelChavePrimariaH1.setText("");
            jCheckBox1.setEnabled(true);
            //jButtonAdicionar.setEnabled(true);
        } catch (Exception e) {
            jLabelChavePrimariaH1.setText("Invalido!");
            jButtonAdicionar.setEnabled(false);
            jCheckBox1.setEnabled(false);
        }
    }//GEN-LAST:event_jTextContactoKeyReleased

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
        jLabelSexo.setForeground(Color.black);
    }//GEN-LAST:event_FemeninoActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
        jLabelSexo.setForeground(Color.black);
    }//GEN-LAST:event_MasculinoActionPerformed

    private void jComboBoxParentescoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxParentescoHActionPerformed
        // TODO add your handling code here:
        if (jComboBoxParentescoH.getSelectedItem().equals("Selecione:")) {
            jLabelGrauParentesco.setForeground(Color.red);
        } else {
            jLabelGrauParentesco.setForeground(Color.black);
        }
    }//GEN-LAST:event_jComboBoxParentescoHActionPerformed

    private void jComboBoxProviniaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProviniaHActionPerformed
        // TODO add your handling code here:
        if (jComboBoxProviniaH.getSelectedItem().equals("Selecione:")) {
                jLabelResiPr.setForeground(Color.red);
            }else{
            jLabelResiPr.setForeground(Color.black);
        }
    }//GEN-LAST:event_jComboBoxProviniaHActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            cbd.pesquisar = cbd.conexao.createStatement();
            String sql = "select max(id) from herdeiro ";
            cbd.resultado = cbd.pesquisar.executeQuery(sql);

            if (cbd.resultado.next()) {               
                jTextContacto.setText(cbd.resultado.getString(1));
            }

        } catch (Exception erro) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
           listaHerdeiroH();        
        }else{
            jButtonAdicionar.setEnabled(false);
        }
         
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Herdeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Herdeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Herdeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Herdeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Herdeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBoxParentescoH;
    private javax.swing.JComboBox<String> jComboBoxProviniaH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAV;
    private javax.swing.JLabel jLabelAviso;
    public static javax.swing.JLabel jLabelBIH;
    private javax.swing.JLabel jLabelChavePrimariaH;
    private javax.swing.JLabel jLabelChavePrimariaH1;
    private javax.swing.JLabel jLabelContacto;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDistMunicipal;
    private javax.swing.JLabel jLabelGrauParentesco;
    private javax.swing.JLabel jLabelLocalidade;
    private javax.swing.JLabel jLabelNome;
    public static javax.swing.JLabel jLabelNomeBenificiarioH;
    private javax.swing.JLabel jLabelResiPr;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTituloH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextAvenidaH;
    private javax.swing.JTextField jTextCasaNumeroH;
    private javax.swing.JTextField jTextContacto;
    private javax.swing.JTextField jTextDistritoMH;
    private javax.swing.JTextField jTextLocalidadeH;
    private javax.swing.JTextField jTextNomeHerdeiro;
    private javax.swing.JTextField jTextquarteraoNumeroH;
    // End of variables declaration//GEN-END:variables
}
