/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMain;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Zona extends javax.swing.JFrame {

    /**
     * Creates new form Zona
     */  
    
    int x,y;
    
    public Zona() {
        initComponents();
        setBackground(new Color(0,0,0,0));

    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fotoeditar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editarnome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editardataaniver = new javax.swing.JLabel();
        editarestadocivil = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editarsexo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editarbi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        editarmae = new javax.swing.JLabel();
        editarpai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editarpais = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Povincia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editarprovincia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editardistrito = new javax.swing.JLabel();
        editarlocalidade = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        editarbairro = new javax.swing.JLabel();
        editarmorada = new javax.swing.JLabel();
        editarBlocalidade = new javax.swing.JLabel();
        editarBdistrito = new javax.swing.JLabel();
        editarBprovincia = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        editarDataRegistada = new javax.swing.JLabel();
        editarhoras = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        editarendtidadetrabalha = new javax.swing.JLabel();
        editarsitucao = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        editarformado = new javax.swing.JLabel();
        editarshowramo = new javax.swing.JLabel();
        lblpatente = new javax.swing.JLabel();
        Vistashowsituacao = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        editarLocalTrabalho = new javax.swing.JLabel();
        editarRamoFADM = new javax.swing.JLabel();
        editarprofissao = new javax.swing.JLabel();
        editarIA = new javax.swing.JLabel();
        ediatarshowdataIA = new javax.swing.JLabel();
        setlocal = new javax.swing.JLabel();
        editarshowlocaltrabalho = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        EditarContacto = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 10, 30, 20));

        fotoeditar.setBackground(new java.awt.Color(0, 204, 204));
        fotoeditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoeditar.setOpaque(true);
        getContentPane().add(fotoeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Nome Completo: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 20));

        editarnome.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 330, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Data de Nascimento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Estado Civil:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 20));

        editardataaniver.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editardataaniver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, 20));

        editarestadocivil.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarestadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 240, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, 20));

        editarsexo.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("BI:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 30, 20));

        editarbi.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Pai:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 30, 20));

        editarmae.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarmae, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 20));

        editarpai.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarpai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Mae:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 40, 20));

        editarpais.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarpais, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 310, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Pais:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 40, 20));

        Povincia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Povincia.setText("Provincia:");
        getContentPane().add(Povincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Distrito:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 60, 20));

        editarprovincia.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarprovincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 260, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Localidade:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, 20));

        editardistrito.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editardistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 280, 20));

        editarlocalidade.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarlocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 260, 20));

        jLabel12.setText("---------------------------------------------Dados do Benificiario----------------------------------------------");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 480, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel21.setText("Distrito:");

        jLabel20.setText("Localidade:");

        jLabel17.setText("Morada:");

        jLabel16.setText("Bairro:");

        jLabel22.setText("Província:");

        editarbairro.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        editarmorada.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        editarBlocalidade.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        editarBdistrito.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        editarBprovincia.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(editarbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(6, 6, 6)
                        .addComponent(editarmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(6, 6, 6)
                        .addComponent(editarBlocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(6, 6, 6)
                        .addComponent(editarBdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(6, 6, 6)
                        .addComponent(editarBprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(editarbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(editarmorada, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(editarBlocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(editarBdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(editarBprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 480, 120));

        jLabel13.setText("--------------------------------------------------Filiação----------------------------------------------------");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 450, -1));

        jLabel14.setText("-----------------------------------------------Naturalidade-------------------------------------------------");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 450, -1));

        jLabel15.setText("---------------------------------------------------Condição------------------------------------------------------");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 450, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Data do Registo:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 120, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Hora:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, 50, -1));

        editarDataRegistada.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarDataRegistada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 700, 90, 20));

        editarhoras.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarhoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 700, 70, 20));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-redimensionar-quatro-sentidos-20.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel24MouseDragged(evt);
            }
        });
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel24MousePressed(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 40, -1));

        editarendtidadetrabalha.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarendtidadetrabalha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 310, 20));

        editarsitucao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(editarsitucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 50, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("Local Onde Trabalha:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 20));

        editarformado.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        editarformado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(editarformado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 270, 20));

        editarshowramo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editarshowramo.setText("Ramo das FADM:");
        getContentPane().add(editarshowramo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 120, 20));

        lblpatente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpatente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblpatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 270, 20));

        Vistashowsituacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Vistashowsituacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Vistashowsituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 270, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Profissão:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 80, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel28.setText("Entidade Onde Trabalha:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 170, 20));

        editarLocalTrabalho.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarLocalTrabalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 330, 20));

        editarRamoFADM.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarRamoFADM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 350, 20));

        editarprofissao.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarprofissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 400, 20));

        editarIA.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editarIA.setText("Data de Incorporacao:");
        getContentPane().add(editarIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 160, 20));

        ediatarshowdataIA.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(ediatarshowdataIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 320, 20));

        setlocal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        setlocal.setText("Local:");
        getContentPane().add(setlocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 60, 20));

        editarshowlocaltrabalho.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(editarshowlocaltrabalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 430, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setText("Contacto:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, 20));

        EditarContacto.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        getContentPane().add(EditarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 130, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/listhow.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        setSize(new java.awt.Dimension(500, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel24MousePressed

    private void jLabel24MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseDragged
        // TODO add your handling code here:
       this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel24MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel EditarContacto;
    private javax.swing.JLabel Povincia;
    public static javax.swing.JLabel Vistashowsituacao;
    private javax.swing.JLabel background;
    public static javax.swing.JLabel ediatarshowdataIA;
    public static javax.swing.JLabel editarBdistrito;
    public static javax.swing.JLabel editarBlocalidade;
    public static javax.swing.JLabel editarBprovincia;
    public static javax.swing.JLabel editarDataRegistada;
    public static transient javax.swing.JLabel editarIA;
    public static javax.swing.JLabel editarLocalTrabalho;
    public static javax.swing.JLabel editarRamoFADM;
    public static javax.swing.JLabel editarbairro;
    public static javax.swing.JLabel editarbi;
    public static javax.swing.JLabel editardataaniver;
    public static javax.swing.JLabel editardistrito;
    public static javax.swing.JLabel editarendtidadetrabalha;
    public static javax.swing.JLabel editarestadocivil;
    public static javax.swing.JLabel editarformado;
    public static javax.swing.JLabel editarhoras;
    public static javax.swing.JLabel editarlocalidade;
    public static javax.swing.JLabel editarmae;
    public static javax.swing.JLabel editarmorada;
    public static javax.swing.JLabel editarnome;
    public static javax.swing.JLabel editarpai;
    public static javax.swing.JLabel editarpais;
    public static javax.swing.JLabel editarprofissao;
    public static javax.swing.JLabel editarprovincia;
    public static javax.swing.JLabel editarsexo;
    public static javax.swing.JLabel editarshowlocaltrabalho;
    public static javax.swing.JLabel editarshowramo;
    public static javax.swing.JLabel editarsitucao;
    public static javax.swing.JLabel fotoeditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblpatente;
    public static javax.swing.JLabel setlocal;
    // End of variables declaration//GEN-END:variables
}
